#!/bin/bash
#SBATCH --time=12:0:0
#SBATCH --account=rrg-skal
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=8GB
#SBATCH --array=0-669

module purge
module load rosetta
module load python/3.8
module load scipy-stack

# This file is intended to be used to make ddg predictions on relaxed structures
# generated by just_relax_cart_s669_inv.sh

### The below section looks up information on the protein like the chain and mutation of interest
IFS=','
# make sure the path s669_mapped.csv is replaced by the actual location
text=$(python -c "import pandas as pd; row = pd.read_csv('./data/s669_mapped.csv').iloc[${SLURM_ARRAY_TASK_ID}, :][['code', 'chain', 'wild_type', 'position', 'mutation', 'mutant_pdb_file', 'offset_rosetta', 'offset_robetta']]; print(','.join([str(i) for i in list(row)]))")
read -a strarr <<< "$text"

code=${strarr[0]}; echo $code
chain=${strarr[1]}; echo $chain
wt=${strarr[2]}; echo $wt
pos=${strarr[3]}; echo $pos
mut=${strarr[4]}; echo $mut
pdb=${strarr[5]}; echo $pdb
offset_ros=${strarr[6]}; echo $offset_ros
offset_rob=${strarr[7]}; echo $offset_rob

# make sure this corresponds to your predictions folder
folder="./predictions/${code}_${chain}/${code}_${pos}${mut}/inv_robetta"

if [ ! -d "$folder" ]; then
  mkdir -p "$folder"
fi

cd "$folder"

minfile=$(ls *_inv_minimized_0001.pdb | head -n 1)
echo $minfile

# sets up the input file that Rosetta will read
ros_pos=$(($pos-$offset_rob))
mutation="$mut$ros_pos$wt"
echo $mutation
echo -e "total 1\n1\n$mutation" > $mutation.mut

start=`date +%s`

### Cartesian ddg protocol from Hoie et al., 2021
$EBROOTROSETTA/bin/cartesian_ddg.mpi.linuxiccrelease \
-in:file:s $minfile \
-database $ROSETTA3_DB \
-ddg:iterations 3 \
-ddg:dump_pdbs true \
-in:missing_density_to_jump \
-ddg:mut_file $mutation.mut \
-ddg:bbnbrs 1 \
-corrections:beta_nov16_cart true \
-packing:ex1 \
-packing:ex2 \
-score:fa_max_dis 9.0 \
-ddg:optimize_proline true \
-ddg:legacy true 
#-ddg:mut_only

end=`date +%s`
runtime=$((end-start))
echo $runtime > 'runtime_'$mutation'_cart_inv.txt'
